### ISSUE TITLE
Feature Request: Users management

### ISSUE THREAD

**Issue by anthosz** [site24x7/terraform-provider-site24x7#148] opened 2022-11-11 10:57 UTC
Hello,

Any plans to add users management via terraform?

The idea is to create/edit/delete users via terraform and "automatize" the group management. Useful when we need to create a lot of users (especially with Alert contact role)

https://www.site24x7.com/help/api/#create-new-user

**Comment by mamoit** [comment] 2022-11-30 12:42
Seems like this is a duplicate of #32.

**Closed** 2022-11-30 12:43 UTC
